### ISSUE TITLE
[Feature Request] Use external links as cover images

### ISSUE THREAD

**Issue by cherinyy** [sharvaridesai/hexo-theme-edinburgh#28]
Hello,

Edinburgh is a great theme, very clean and simple, but it doesn't seem to be able to use external links as cover images. It would be great if this feature could be implemented.

Best regards,
wordlesswind

**Comment by wordlesswind** [comment]
It seems that @sharvaridesai has not been active on GitHub for a long time, so I will try to [fork this theme](https://github.com/wordlesswind/hexo-theme-edinburgh) and add this feature.
