### ISSUE TITLE
About the image

### ISSUE THREAD

**Issue by lookatseventeen** [sharvaridesai/hexo-theme-edinburgh#8]
Specify your own image like this.

cover_image: /images/portfolio.jpg

I don't know how to set the image, where to put the images? thanks!

**Comment by ucasfl** [comment]
I have the same problem about how to set the image. @sharvaridesai

**Comment by sharvaridesai** [comment]
You can put images in your Hexo source folder. For the example code above, you would put the image at /source/images/portfolio.jpg
